package nl.dare2date.matching.interests;

/**
 * Created by Bas on 5-10-2015.
 */
public enum InterestType {
    CHANNEL,
    MUSIC,
    MOVIE,
    TVSERIES,
    BOOK,
    SPORT,
    GAME,
    ANIMAL,
    CREATIVE,
    COLLECTION,
    CULTURE,
    TINKERING,
    TRAVEL, COMPUTERS, SOCIAL, TRANSPORTATION, KIDS, PHOTOGRAPHY, HUMANITARIAN, FOOD, CLOTHING, COLOR, THEATHER, COMMUNITY, POLITICS, HEALTH, NATURE, ART, OTHER

}
